name: Deploy to Komodo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Komodo Deployment
        run: |
          curl -X POST "${{ secrets.KOMODO_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          --fail \
          --verbose